services:
  - type: web
    name: emi-pro
    env: node
    region: oregon
    plan: free
    rootDir: .
    buildCommand: npm install && npm install --prefix backend
    startCommand: node backend/server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: PROVISIONING_DEVICE_ADMIN_SIGNATURE_CHECKSUM
        value: 9MBtfICaLx0RVCoQ4oNB1DNh-FCGkLPc3dRNCLnVHJc
      - key: PROVISIONING_BASE_URL
        value: https://emi-pro-app.onrender.com
